feat: tranche assets W12-43
w12-platform/W12-Product-Blockchain-User-Interfaces pull request #48
Opened 2018-10-31 18:52 UTC by Semapl3

2018-10-31 19:20 UTC, Hokid requested changes

2018-10-31 19:20 UTC, Hokid commented on src/bem/TrancheInformation/0.27.1/index.vue
> +                    this.trancheInformationData.trancheInfo.forEach((info)=>{
у массива есть метод `some`, кот. вернет `true` если хоть для 1 из элементов массива коллбэк вернет `true`

2018-10-31 19:20 UTC, Hokid commented on src/bem/TrancheInformation/0.27.1/index.vue
> +                    const trancheIntervals = this.currentProject.crowdSaleInformation.tokenCrowdSaleMilestones
Есть предложение. Можно вот такие вот операции над данными(нужно что-то получить из чего-то) выносить в функции, в `lib/selectors`. Думаю, так удобней будет и понятней. Идея с "селекторами" взята из https://github.com/reduxjs/reselect.

2018-10-31 19:20 UTC, Hokid commented on src/store/modules/Project.js
> +                    const getTotalFundedAssetsSymbolsPromise = getTotalFundedAssetsSymbols.map(async (symbol)=>{
Ты как-то подклучил `p-iteration` билблиотеку, давай ее юзать везде? она удобная

2018-10-31 19:20 UTC, Hokid commented on src/store/modules/Project.js
> +                            "TotalFundedAmount": (fromWeiDecimals(totalAmount, 18)).toString(),
Тут не правильно переводим по decimals. У каждого ассета может быть свой десятичный указатель, и он может быть отличен  от 18(токены с разными decimals). Плюс getTotalFundedAssetsSymbols возвращает еще такой специфичный символ USD- у него decimals 8. Для того, чтобы узнать decimals для какого-либо ассета, нужно вызвать action `rasolveDecimals` у Rates модуля, он как раз вернет правильный. Кстати я добавлял 2-е функции convertionByDecimals и reverseConversionByDecimals, что означает конвертирова значение по decimals и обратное конвертирование по decimals - может их здесь использовать?

2018-10-31 19:20 UTC, Hokid commented on src/store/modules/Project.js
> +                            "TotalFundedAmount": (fromWeiDecimals(totalAmount, 18)).toString(),
И еще нужно(пока в контракте не добавили метод) уменьшать доступную долю для трашши в ассете на долу возвращенных токенов. trancheAmount = trancheAmount * totalTokenRefunded/ totalTokenBought. totalTokenRefunded, totalTokenBought - публичные данные контракта фонда.

2018-10-31 19:20 UTC, Hokid commented on src/bem/TrancheInformation/0.27.1/index.vue
> +                    const tx = await W12Fund.methods.tranche({from: this.currentAccount});
А тут ивент не нужно разве ждать для надежности?

2018-11-01 20:40 UTC, Semapl3 commented on src/bem/TrancheInformation/0.27.1/index.vue
> +                    const tx = await W12Fund.methods.tranche({from: this.currentAccount});
ивент чуть выше по логике в ProjectDashboardTranche

2018-11-01 20:41 UTC, Semapl3 commented on src/store/modules/Project.js
> +                            "TotalFundedAmount": (fromWeiDecimals(totalAmount, 18)).toString(),
+

2018-11-01 20:41 UTC, Semapl3 commented on src/store/modules/Project.js
> +                    const getTotalFundedAssetsSymbolsPromise = getTotalFundedAssetsSymbols.map(async (symbol)=>{
+

2018-11-01 20:41 UTC, Semapl3 commented on src/bem/TrancheInformation/0.27.1/index.vue
> +                    this.trancheInformationData.trancheInfo.forEach((info)=>{
+

2018-11-02 02:22 UTC, Hokid requested changes

2018-11-02 02:22 UTC, Hokid commented on crowdsale.html
> -<script src="node_modules/moment/moment.js"></script>
Можешь, пожалуйста, вынести отдельным PR эти изменения, они от другой задачи. Для релиза после выхода новой версии формируется changelog на основе коммитов и нужно стараться, чтобы в него попадали номера задач. Так бы если в коммите было указано к какой задаче относятся изменения, то не страшно, можно оставить, но тут придется PR, чтобы потом сделать мерж коммит с номером задачи.

2018-11-02 02:22 UTC, Hokid commented on package.json
> +  "version": "0.8.0-alpha.0",
Вот это нужно вернуть обратно

2018-11-02 10:09 UTC, closed without merging