feat: [W12-187] Cache
w12-platform/W12-Product-Blockchain-User-Interfaces pull request #93
Opened 2018-11-26 19:41 UTC by Semapl3

/src/lib/Blockchain/Cache.js

Указанные в функции getCacheMap названия методов с типом permanent будут кешироваться постоянно до момента их ручного удаления либо до обновления версии в package.json

Версия -> Название контракта -> Массив имен методов
```
"0.20.5": {
  WToken: ['name', 'symbol', 'decimals', 'owner'],
},
```
Остальные методы имеющие в abi type === function и constant === true будут кешироваться по номеру последнего блока в сети.

2018-11-26 23:23 UTC, Hokid requested changes

2018-11-26 23:23 UTC, Hokid commented on src/lib/Blockchain/Wrappers/0.21.3/W12Crowdsale.js
> +                    endDate: new BigNumber(milestone[0]).toNumber(),
В обертке BigNumber нет необходимости, т.к. по умолчанию для number web3 возвратит BigNumber

2018-11-26 23:23 UTC, Hokid commented on src/bem/RefundEth/index.vue
> +                    await this.$store.dispatch('Cache/blockNumberUp');
А зачем это вручную делать, там же есть startWatchBlockNumberUpdate?

2018-11-26 23:23 UTC, Hokid commented on src/lib/Blockchain/Cache.js
> +                WToken: ['name', 'symbol', 'decimals', 'owner'],
owner, теоритически, может поменятся

2018-11-26 23:23 UTC, Hokid commented on src/lib/Blockchain/Cache.js
> +                W12Crowdsale: ['originToken', 'WTokenSaleFeePercent', 'version', 'serviceWallet',
price может менятся

2018-11-26 23:23 UTC, Hokid commented on src/lib/Blockchain/Cache.js
> +                W12TokenLedger: ['getWTokenByToken', 'getTokenByWToken', 'owner', 'version'],
В этой версии TokenExchanger должен быть

2018-11-26 23:23 UTC, Hokid commented on src/lib/Blockchain/Cache.js
> +                W12Lister: ['version', 'exchanger', 'serviceWallet', 'owner', 'factory', 'getTokenCrowdsale',
owner может меняться

2018-11-26 23:23 UTC, Hokid commented on src/lib/Blockchain/Cache.js
> +                W12Lister: ['version', 'exchanger', 'serviceWallet', 'owner', 'factory', 'getTokenCrowdsale',
getTokenCrowdsale может закешировать 0x0 адрес, и возвращает его всегда, т.к. агрументы при запросе теже, а кровдсейл может к тому времени быть инициализирован и иметь адрес

2018-11-26 23:23 UTC, Hokid commented on src/lib/Blockchain/Cache.js
> +                IW12Crowdsale: ['getWToken'],
А в коде IW12... используем, вроде бы W12Crowdsale?

2018-11-26 23:23 UTC, Hokid commented on src/lib/Blockchain/Cache.js
> +export function getCacheMap() {
Давай это в конфиг вынесем, чтобы не отдавать каждый раз новый объект с одним и темже контентом.

2018-11-26 23:23 UTC, Hokid commented on src/lib/Blockchain/Cache.js
> +        if (methods && methods.find(item => item === method)) {
можно использовать .includes, вместо find

2018-11-26 23:23 UTC, Hokid commented on src/lib/Blockchain/Wrappers/NoVersion/BaseWrapper.js
> +                    methods[item.name] = cacheController({
Давай еще помимо установки, что кешировать через настройки,  сделаем опционально прием типа кэша из агрумента опций при вызове метода контракта:

Contract.methods.someMethod(arg1, arg2, { value: '1', cache: '<CACHE TYPE>' })

если установлен, то применяем этот вид каше несмотря на настройки. Если не установлен берем из настроек.

2018-11-26 23:23 UTC, Hokid commented on src/lib/utils.js
> +    console.log(e);
В нек. местах мы можем сами логировать ошибку + еще тут будет дублироваться. Давай уберем тут.

2018-11-26 23:23 UTC, Hokid commented on src/store/modules/Cache.js
> +        get({state}, hash) {
Эту нужно вынести в геттер

2018-11-27 05:53 UTC, Semapl3 commented on src/lib/Blockchain/Wrappers/0.21.3/W12Crowdsale.js
> +                    endDate: new BigNumber(milestone[0]).toNumber(),
Но теперь там может быть и строка из кеша, в кеш сохраняется строка

2018-11-27 05:54 UTC, Semapl3 commented on src/bem/RefundEth/index.vue
> +                    await this.$store.dispatch('Cache/blockNumberUp');
Потому что есть небольшая вероятность при обновлении данных получить старые из кеша, поэтому принудительно сбрасываем кеш

2018-11-27 05:55 UTC, Semapl3 commented on src/lib/Blockchain/Cache.js
> +                WToken: ['name', 'symbol', 'decimals', 'owner'],
ок

2018-11-27 05:56 UTC, Semapl3 commented on src/lib/Blockchain/Cache.js
> +                W12Crowdsale: ['originToken', 'WTokenSaleFeePercent', 'version', 'serviceWallet',
ок

2018-11-27 06:55 UTC, Hokid commented on src/lib/Blockchain/Wrappers/0.21.3/W12Crowdsale.js
> +                    endDate: new BigNumber(milestone[0]).toNumber(),
Точно. Слушай, может мы будем сериализовывать данные, указывая тип, а при извлечении десериализацию делать по типу, указаному нами и отдавать то, что нужно? Чтобы не было похоже, что у нас кэш под капотом и мы не думали о том, что он может дать нам не то, что мы ожидаем. Мне кажется это сохранить пару нервов)

2018-11-27 06:57 UTC, Hokid commented on src/bem/RefundEth/index.vue
> +                    await this.$store.dispatch('Cache/blockNumberUp');
Так можно при получении даных из кэша делать этот запрос, чтобы всегда быть уверенным, что мы имее последний блок. Просто мы при добавлении нового кода забудем об этой строке как-нибудь)

2018-11-27 08:04 UTC, Semapl3 commented on src/store/modules/Cache.js
> +        get({state}, hash) {
Это не совсем вычисляемое свойство, в данном случае удобней использовать dispatch а getters не доступен через dispatch

2018-11-27 08:04 UTC, Semapl3 commented on src/lib/utils.js
> +    console.log(e);
ок

2018-11-27 08:14 UTC, Hokid commented on src/store/modules/Cache.js
> +        get({state}, hash) {
Это как раз геттер, офф. док. предлагает такой способ:

getters: {
  get(state, getters) { return (hash) => state.results.find(i => i.hash === hash) }
}

2018-11-27 12:01 UTC, Semapl3 commented on src/lib/Blockchain/Wrappers/NoVersion/BaseWrapper.js
> +                    methods[item.name] = cacheController({
Пример:
`const name = await this.methods.name({cache: 'permanent'});`

2018-11-27 14:52 UTC, closed without merging