feat: [W12-197] Cache
w12-platform/W12-Product-Blockchain-User-Interfaces pull request #94
Opened 2018-11-27 14:38 UTC by Semapl3

2018-11-27 16:43 UTC, Belkad approved these changes

2018-11-27 16:43 UTC, Belkad approved these changes

2018-11-28 02:29 UTC, Hokid requested changes
См. проблемы в PR в stage

2018-11-28 02:37 UTC, Hokid requested changes

2018-11-28 02:37 UTC, Hokid commented on src/lib/Blockchain/Cache.js
> +                console.log(data.result);
убрать нужно или применить спец. функции для логирования в dev окружении(см. lib/dev.js)

2018-11-28 02:37 UTC, Hokid commented on src/lib/Blockchain/Cache.js
> +                    console.log(data.meta.typesOutput);
убрать нужно или применить спец. функции для логирования в dev окружении(см. lib/dev.js)

2018-11-29 10:29 UTC, Hokid commented
Moved to #96

2018-11-29 10:29 UTC, closed without merging